name: AntiSwear
version: '1.0'
main: com.antiswear.AntiSwear
api-version: '1.20'
authors: [meqxs]
description: A plugin that filters swear words from chat and logs violations
depend: []
softdepend: [] 